### ISSUE TITLE
Overlap removal can't cope with quadratic sources

### ISSUE THREAD

**Issue by simoncozens** [googlefonts/ufo2ft#468]
```
ERROR:ufo2ft.filters.removeOverlaps:Failed to remove overlaps for A
fontmake: Error: In 'Arimo-Bold.glyphs' -> 'master_ufo/Arimo-Bold.designspace' -> 'master_ufo/Arimo-Bold.ufo': Compiling UFO failed: ('Trying to perform operation on unsupported segment type.', 'qcurve')
```

Perhaps we need a quadratic to cubic filter...

**Comment by anthrotype** [comment]
booleanOperations doesn't support qcurve. It works if you use pathops instead via the `overlapsBackend` option to compile* functions:

https://github.com/googlefonts/ufo2ft/blob/master/Lib/ufo2ft/__init__.py#L171

It should be documented better, I know.

Fontmake also has an --overlaps-backend option that uses that.

**Comment by anthrotype** [comment]
> a quadratic to cubic filter...

I never finished this https://github.com/googlefonts/cu2qu/pull/29  -- it lacks logic to split until below error tolerance, right now it assumes the quads were originally converted from cubics rather than hand-drawn (or post-processed afterwards).

**Comment by jenskutilek** [comment]
Trying to use pathops to remove overlaps in a quadratic UFO ... still no success. Any way to debug this?

```
fontmake -u M-5Regular.ufo --keep-direction --output-dir ro -o ttf --overlaps-backend pathops --verbose DEBUG
DEBUG:fontmake.font_project:ufoLib UFO validation is disabled
INFO:fontmake.font_project:Building TTF for M-Regular
INFO:ufo2ft:Pre-processing glyphs
DEBUG:ufo2ft.filters.removeOverlaps:using skia-pathops as RemoveOverlapsFilter backend
INFO:ufo2ft.filters:Running DecomposeComponentsFilter on M-Regular
INFO:ufo2ft.filters:Running RemoveOverlapsFilter on M-Regular
ERROR:root:In 'M-5Regular.ufo': Compiling UFO failed
Traceback (most recent call last):
  File "/Users/kuti/Code/variable-fonts/env3.10a/lib/python3.10/site-packages/fontmake/font_project.py", line 439, in _iter_compile
    yield compile_func(ufo, debugFeatureFile=debugFeatureFile, **options)
  File "/Users/kuti/Code/variable-fonts/env3.10a/lib/python3.10/site-packages/ufo2ft/__init__.py", line 247, in compileTTF
    glyphSet = call_preprocessor(ufo, **kwargs)
  File "/Users/kuti/Code/variable-fonts/env3.10a/lib/python3.10/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/Users/kuti/Code/variable-fonts/env3.10a/lib/python3.10/site-packages/ufo2ft/__init__.py", line 73, in call_preprocessor
    return preProcessor.process()
  File "/Users/kuti/Code/variable-fonts/env3.10a/lib/python3.10/site-packages/ufo2ft/preProcessor.py", line 101, in process
    func(ufo, glyphSet)
  File "/Users/kuti/Code/variable-fonts/env3.10a/lib/python3.10/site-packages/ufo2ft/filters/base.py", line 207, in __call__
    if include(glyph) and filter_(glyph):
  File "/Users/kuti/Code/variable-fonts/env3.10a/lib/python3.10/site-packages/ufo2ft/filters/removeOverlaps.py", line 47, in filter
    self.union(contours, pen)
  File "/Users/kuti/Code/variable-fonts/env3.10a/lib/python3.10/site-packages/pathops/operations.py", line 31, in union
    path = _draw(contours)
  File "/Users/kuti/Code/variable-fonts/env3.10a/lib/python3.10/site-packages/pathops/operations.py", line 18, in _draw
    contour.draw(pen)
  File "/Users/kuti/Code/variable-fonts/env3.10a/lib/python3.10/site-packages/ufoLib2/objects/contour.py", line 157, in draw
    self.drawPoints(pointPen)
  File "/Users/kuti/Code/variable-fonts/env3.10a/lib/python3.10/site-packages/ufoLib2/objects/contour.py", line 182, in drawPoints
    pointPen.endPath()
  File "/Users/kuti/Code/variable-fonts/env3.10a/lib/python3.10/site-packages/fontTools/pens/pointPen.py", line 155, in endPath
    self._flushContour(segments)
  File "/Users/kuti/Code/variable-fonts/env3.10a/lib/python3.10/site-packages/fontTools/pens/pointPen.py", line 234, in _flushContour
    pen.qCurveTo(*points)
  File "src/python/pathops/_pathops.pyx", line 902, in pathops._pathops.PathPen.qCurveTo
  File "src/python/pathops/_pathops.pyx", line 1264, in pathops._pathops._decompose_quadratic_segment
AssertionError
```

**Comment by anthrotype** [comment]
@jenskutilek it's as if skia-pathops is being called with a `pen.qCurveTo(*points)` method where the number of points is 0... how is that even possible?

**Comment by anthrotype** [comment]
the RemoveOverlapsFilter only catches PathOpsError, maybe you can hack it to also catch AssertionError like so:

https://github.com/googlefonts/ufo2ft/blob/9b5017719d5a30ab3cda1b6fdaa83c2cbf5d5834/Lib/ufo2ft/filters/removeOverlaps.py#L48

```diff
         try:
             self.union(contours, pen)
-        except self.Error:
+        except (self.Error, AssertionError):
             logger.error("Failed to remove overlaps for %s", glyph.name)
```

at least you know the name of the offending glyph...

**Comment by anthrotype** [comment]
if it turns out to be something that happens on a regular basis with valid source files, we may consider modifying pathops to instead raise a PathOpsError exception instead of AssertionError (which by definition is supposed to _never_ be raised neither in normal nor exceptional circumstances)

**Comment by jenskutilek** [comment]
It seems to work in most cases, but some specific glyphs in the UFO fail ... will investigate

**Comment by jenskutilek** [comment]
It seems the UFO was indeed buggy and had a "qcurve" segment without any offcurve points.

**Comment by anthrotype** [comment]
how does that look? Can you paste a snippet? And, was it authored by hand or emitted by a font editor?

**Comment by anthrotype** [comment]
I think a point whose segment type is "qcurve" that is not preceded by any off-curve should be interpreted as a straght line, at least that's what the UFO spec says about "curve" (which I would assume should apply to "qcurve" as well):

https://unifiedfontobject.org/versions/ufo3/glyphs/glif/#point-types

So arguably it's not the UFO that's buggy since the spec seems to allow that, but the code should be made smarter

**Comment by jenskutilek** [comment]
The UFO was generated by newish custom code ;) RoboFont indeed interprets the segment as a straight line, that's why it wasn't noticeable just by looking at the curves.

**Comment by jenskutilek** [comment]
```xml
<?xml version='1.0' encoding='UTF-8'?>
<glyph name="R.sc" format="2">
  <advance width="2276"/>
  <outline>
    <contour>
      <point x="367" y="12" type="qcurve"/>
      <point x="367" y="70"/>
      <point x="368" y="450"/>
      <point x="368" y="1705"/>
      <point x="367" y="2085"/>
      <point x="367" y="2143" type="qcurve"/>
      <point x="367" y="2155"/>
      <point x="379" y="2155" type="qcurve"/>
      <point x="1092" y="2155" type="line"/>
      <point x="1272" y="2155"/>
      <point x="1559" y="2103"/>
      <point x="1777" y="1998"/>
      <point x="1924" y="1841"/>
      <point x="1998" y="1634"/>
      <point x="1998" y="1507" type="qcurve"/>
      <point x="1998" y="1378"/>
      <point x="1923" y="1169"/>
      <point x="1774" y="1009"/>
      <point x="1549" y="900"/>
      <point x="1254" y="845"/>
      <point x="1077" y="845" type="qcurve"/>
      <point x="705" y="845" type="line"/>
      <point x="707" y="12" type="line"/>
      <point x="707" y="0"/>
      <point x="695" y="0" type="qcurve"/>
      <point x="379" y="0" type="line"/>
      <point x="367" y="0"/>
    </contour>
    <contour>
      <point x="705" y="1106" type="line"/>
      <point x="1088" y="1106" type="qcurve"/> <!-- ERROR -->
      <point x="1198" y="1106"/>
      <point x="1371" y="1136"/>
      <point x="1505" y="1198"/>
      <point x="1596" y="1292"/>
      <point x="1643" y="1419"/>
      <point x="1643" y="1499" type="qcurve"/>
      <point x="1643" y="1579"/>
      <point x="1596" y="1707"/>
      <point x="1505" y="1802"/>
      <point x="1371" y="1863"/>
      <point x="1198" y="1893"/>
      <point x="1088" y="1893" type="qcurve"/>
      <point x="705" y="1893" type="line"/>
    </contour>
    <contour>
      <point x="1729" y="0" type="line"/>
      <point x="1714" y="0"/>
      <point x="1704" y="11" type="qcurve"/>
      <point x="956" y="929" type="line"/>
      <point x="1349" y="929" type="line"/>
      <point x="2121" y="19" type="line"/>
      <point x="2138" y="0"/>
      <point x="2113" y="0" type="qcurve"/>
    </contour>
  </outline>
</glyph>
```

**Comment by anthrotype** [comment]
@jenskutilek take a look at https://github.com/fonttools/skia-pathops/pull/63, should fix that bug

**Comment by anthrotype** [comment]
@jenskutilek looks like it works with that patch, see

```
$ python -m ufo2ft.filters PathOpsBuggy.ufo 'RemoveOverlapsFilter(backend="pathops")'
INFO:ufo2ft.filters:Running RemoveOverlapsFilter on PathOpsBug
INFO:ufo2ft.filters:Written on PathOpsBuggy#1.ufo
```

**Comment by anthrotype** [comment]
@jenskutilek try with https://github.com/fonttools/skia-pathops/releases/tag/v0.7.4

**Comment by jenskutilek** [comment]
Yes, it works. Thank you very much!

I noticed something else (also with previous versions), in most round corners with acute angles, additional points are inserted when removing overlaps. Is this expected?

Before:

![Bildschirm­foto 2022-11-16 um 08 31 11](https://user-images.githubusercontent.com/3185950/202115358-3623ffd1-6c0e-4070-9dd5-16d218cbc904.png)

After:

![Bildschirm­foto 2022-11-16 um 08 29 04](https://user-images.githubusercontent.com/3185950/202115398-1f94cded-4ffd-4fe7-b10c-fc31fafaea4a.png)
